### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [plotly/react-cytoscapejs#20]
Using plain JavaScript cytoscape can render composite structures:
```jsx
cytoscape({
    container: document.getElementById('cy'),
    elements:[
      { data: { id: 'a', parent: 'b' } },
      { data: { id: 'b' } },
      { data: { id: 'c', parent: 'b' } },
      { data: { id: 'd' } },
      { data: { id: 'e' } },
      { data: { id: 'f', parent: 'e' } },
      { data: { id: 'ad', source: 'a', target: 'd' } },
      { data: { id: 'eb', source: 'e', target: 'b' } }
    ],
    layout: { name: "grid" }
  });
```

Working example in https://codepen.io/anon/pen/Oqdqjj

But when using react-cytoscapejs:
```jsx
import * as React from 'react';
import CytoscapeComponent from 'react-cytoscapejs';

class App extends React.Component {
  public render() {
    return (
      <CytoscapeComponent 
        elements={ 
          [
            { data: { id: 'a', parent: 'b' } },
            { data: { id: 'b' } },
            { data: { id: 'c', parent: 'b' } },
            { data: { id: 'd' } },
            { data: { id: 'e' } },
            { data: { id: 'f', parent: 'e' } },
            { data: { id: 'ad', source: 'a', target: 'd' } },
            { data: { id: 'eb', source: 'e', target: 'b' } }
          ]
        } 
        layout={ {name: "grid"} }
      />
    );
  }
}

export default App;
```
I'm getting exception:
![image](https://user-images.githubusercontent.com/720999/56085164-a9b58000-5e36-11e9-8c43-387c1bc5e52e.png)

**Comment by pcapillon** [comment]
I stumbled upon the same issue and traced it to npm installing a more recent branch of cytoscape than 3.2.x (I had 3.5.7 installed). I fixed it by capping the version to cytoscape@3.2.22, but did not trace which branch/update broke composite structures (`npm install cytoscape@3.2.22` or change `package.json` to have `"cytoscape": "~3.2.22"`).

More accurately, composite structures work as long as edges do not leave each group. Edges work fine within a group of nodes.

**Comment by KrzysztofKowalczyk** [comment]
@pcapillon thanks, I will try in free time, I definitely cross boundaries between groups.

**Comment by priomsrb** [comment]
I'm facing this same error when crossing boundaries between groups. Since this bug still occurs in the latest version, should this issue be re-opened?

**Comment by maxkfranz** [comment]
Follow the usage instructions: https://github.com/plotly/react-cytoscapejs#usage

Install the version of `cytoscape` that's appropriate for your app.  You shouldn't rely on implicit installations by npm.

**Comment by priomsrb** [comment]
Thanks for your reply. I tried installing the latest version of cytoscape
in my package.json. If I use my code in vanilla (i.e. jQuery) cytoscape it
works. But with this react version it fails. I'll have another look to see
if I can figure out what's going on.

**Comment by priomsrb** [comment]
I figured out the cause. It happens because we [perform a layout inside `cy.batch()`](https://github.com/plotly/react-cytoscapejs/blob/b8578ffb90c7acd4da93e536bde7c897d8d217b2/src/patch.js#L65). Here is a minimal example that reproduces this error ([codepen](https://codepen.io/priomsrb/pen/LYPXbQK?editors=1000)):

```
var elements = [
    { data: { id: 'a', parent: 'b' }},
    { data: { id: 'b' } },
    { data: { id: 'c' }},
    { data: { id: 'ac', source: 'a', target: 'c' } },
];

var cy = window.cy = cytoscape({ container: document.getElementById('cy') });

cy.batch(() => {
    cy.add(elements)

    // This next line will cause an error if inside cy.batch()
    cy.layout({ name: 'random' }).run();
});
```
cytoscape's docs about [batch](http://js.cytoscape.org/#cy.batch) mention that it is for manipulating elements, but it doesn't mention anything about layouts. So maybe the `cy.layout()` call should be moved out of the batch.

Let me know if moving the layout out of the batch sounds like a good solution to you. If so, I can try putting up a pull request.

**Comment by priomsrb** [comment]
As mentioned in https://github.com/cytoscape/cytoscape.js/issues/2528#issuecomment-534153446 layouts shouldn't be run inside a batch. So to fix this error, layouting should be moved outside batch calls inside react-cytoscapejs.

**Comment by maxkfranz** [comment]
Layout wasn't originally intended to be patchable.  Probably only this section should be batched:

https://github.com/plotly/react-cytoscapejs/blob/v1.2.0/src/patch.js#L8-L21
